/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.favaunt.forms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Timestamp;
import javax.swing.JOptionPane;

/**
 *
 * @author deepratnaawale
 */
public class RegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form QueryForm
     */
    public RegistrationForm() {
        initLookAndFeel();
        initComponents();
        newRegisterationFormPanel.setVisible(false);
    }

    private void initLookAndFeel() {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DischargeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        newRegistrationBtn = new javax.swing.JButton();
        registeredPatients = new javax.swing.JButton();
        newRegisterationFormPanel = new javax.swing.JPanel();
        patientName = new javax.swing.JTextField();
        patientAge = new javax.swing.JTextField();
        patientGender = new javax.swing.JTextField();
        patientBloodGroup = new javax.swing.JTextField();
        patientPhoneNumber = new javax.swing.JTextField();
        patientAddress = new javax.swing.JTextField();
        patientNameLbl = new javax.swing.JLabel();
        patientDobLbl = new javax.swing.JLabel();
        patientGenderLbl = new javax.swing.JLabel();
        patientBloodGrpLbl = new javax.swing.JLabel();
        patientPhoneNumberLbl = new javax.swing.JLabel();
        patientAddressLbl = new javax.swing.JLabel();
        PatientRegisterBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        patientComments = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setResizable(false);

        newRegistrationBtn.setText("New Registeration");
        newRegistrationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRegistrationBtnActionPerformed(evt);
            }
        });

        registeredPatients.setText("Registered Patients");
        registeredPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registeredPatientsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registeredPatients)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newRegistrationBtn)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newRegistrationBtn)
                    .addComponent(registeredPatients))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        patientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientNameActionPerformed(evt);
            }
        });

        patientGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientGenderActionPerformed(evt);
            }
        });

        patientBloodGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientBloodGroupActionPerformed(evt);
            }
        });

        patientPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientPhoneNumberActionPerformed(evt);
            }
        });

        patientAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientAddressActionPerformed(evt);
            }
        });

        patientNameLbl.setText("Patient Name:");

        patientDobLbl.setText("Age:");

        patientGenderLbl.setText("Gender:");

        patientBloodGrpLbl.setText("Blood Group:");

        patientPhoneNumberLbl.setText("Phone Number:");

        patientAddressLbl.setText("Address:");

        PatientRegisterBtn.setText("Register");
        PatientRegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientRegisterBtnActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Contact");

        patientComments.setForeground(new java.awt.Color(204, 204, 204));
        patientComments.setToolTipText("Comments Here");
        patientComments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientCommentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newRegisterationFormPanelLayout = new javax.swing.GroupLayout(newRegisterationFormPanel);
        newRegisterationFormPanel.setLayout(newRegisterationFormPanelLayout);
        newRegisterationFormPanelLayout.setHorizontalGroup(
            newRegisterationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newRegisterationFormPanelLayout.createSequentialGroup()
                .addGroup(newRegisterationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newRegisterationFormPanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(newRegisterationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(patientNameLbl)
                            .addComponent(patientDobLbl)
                            .addComponent(patientGenderLbl)
                            .addComponent(patientBloodGrpLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newRegisterationFormPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(newRegisterationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientAddressLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(patientPhoneNumberLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(newRegisterationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(patientName)
                    .addComponent(patientAge)
                    .addComponent(patientBloodGroup)
                    .addComponent(patientPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientGender, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(newRegisterationFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newRegisterationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newRegisterationFormPanelLayout.createSequentialGroup()
                        .addComponent(patientAddress)
                        .addContainerGap())
                    .addGroup(newRegisterationFormPanelLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newRegisterationFormPanelLayout.createSequentialGroup()
                        .addGroup(newRegisterationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newRegisterationFormPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(newRegisterationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator5)
                                    .addComponent(patientComments)))
                            .addGroup(newRegisterationFormPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(PatientRegisterBtn)))
                        .addGap(17, 17, 17))))
        );
        newRegisterationFormPanelLayout.setVerticalGroup(
            newRegisterationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newRegisterationFormPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(newRegisterationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientNameLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newRegisterationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientDobLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newRegisterationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientGenderLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newRegisterationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientBloodGrpLbl)
                    .addComponent(patientBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(newRegisterationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newRegisterationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientPhoneNumberLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(patientAddressLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(patientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientComments, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PatientRegisterBtn)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(newRegisterationFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newRegisterationFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registeredPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registeredPatientsActionPerformed
        // TODO add your handling code here:
        RegisteredPatients registeredPatients = new RegisteredPatients();
        registeredPatients.setVisible(true);

    }//GEN-LAST:event_registeredPatientsActionPerformed

    private void newRegistrationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRegistrationBtnActionPerformed
        newRegisterationFormPanel.setVisible(true);
    }//GEN-LAST:event_newRegistrationBtnActionPerformed

    private void patientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientNameActionPerformed

    private void patientBloodGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientBloodGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientBloodGroupActionPerformed

    private void patientPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientPhoneNumberActionPerformed

    private void PatientRegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientRegisterBtnActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/db_base", "root", "toor");
            PreparedStatement statement = conn.prepareStatement("Insert  into PATIENT_DATABASE (patientName, patientAge, patientGender, patientBloodGroup, patientPhoneNumber, patientAddress, patientComments, patientAdmissionDate)values (?,?,?,?,?,?,?,?)");

            statement.setString(1, patientName.getText());
            statement.setString(2, patientAge.getText());
            statement.setString(3, patientGender.getText());
            statement.setString(4, patientBloodGroup.getText());
            statement.setString(5, patientPhoneNumber.getText());
            statement.setString(6, patientAddress.getText());
            statement.setString(7, patientComments.getText());
            statement.setTimestamp(8, new Timestamp(System.currentTimeMillis()));
            statement.executeUpdate();

            JOptionPane.showMessageDialog(null, "Registeration Successful.");

            patientName.setText("");
            patientAddress.setText("");
            patientAge.setText("");
            patientGender.setText("");
            patientBloodGroup.setText("");
            patientPhoneNumber.setText("");
            patientComments.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
    }//GEN-LAST:event_PatientRegisterBtnActionPerformed

    private void patientCommentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientCommentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientCommentsActionPerformed

    private void patientAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientAddressActionPerformed

    private void patientGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientGenderActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PatientRegisterBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPanel newRegisterationFormPanel;
    private javax.swing.JButton newRegistrationBtn;
    private javax.swing.JTextField patientAddress;
    private javax.swing.JLabel patientAddressLbl;
    private javax.swing.JTextField patientAge;
    private javax.swing.JTextField patientBloodGroup;
    private javax.swing.JLabel patientBloodGrpLbl;
    private javax.swing.JTextField patientComments;
    private javax.swing.JLabel patientDobLbl;
    private javax.swing.JTextField patientGender;
    private javax.swing.JLabel patientGenderLbl;
    private javax.swing.JTextField patientName;
    private javax.swing.JLabel patientNameLbl;
    private javax.swing.JTextField patientPhoneNumber;
    private javax.swing.JLabel patientPhoneNumberLbl;
    private javax.swing.JButton registeredPatients;
    // End of variables declaration//GEN-END:variables
}
